embulk-output-jdbc/src/main/java/org/embulk/output/JdbcOutputPlugin.java, embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
Some dbms plugins cannot offer JDBC driver because of a license.
In such a case, a user should download the JDBC driver and set the path of the driver to yml, and the plugin should add the path to the PluginClassLoader.
So it is convenient if the AbstractJdbcOutputPlugin class offer loadDriverJar method (now implemented in the JdbcOutputPlugin class).
=> Enable subclasses of AbstractJdbcOutputPlugin to use loadDriverJar method

embulk-output-mysql/README.md, embulk-output-postgresql/README.md
This PR updates README to add new *merge* mode for mysql/postgresql.
=> update docs for merge mode

embulk-output-redshift/build.gradle
Similar fix to embulk/embulk-input-s3#16.
=> Update aws-java-sdk version

embulk-output-mysql/README.md, embulk-output-oracle/README.md, embulk-output-postgresql/README.md, embulk-output-redshift/README.md
=> fixed description about 'replace' mode

embulk-output-sqlserver/src/main/java/org/embulk/output/SQLServerOutputPlugin.java
can't only specify the "instance"
=> sqlserver: specify "port" or "instance"

embulk-output-sqlserver/README.md
I'll write readme for other embulk-output-xxx plugins.
=> README for supported types in embulk-output-sqlserver

embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/setter/ColumnSetterFactory.java, embulk-output-oracle/README.md
and update README for supported types in embulk-output-oracle.
=> Support NCLOB

embulk-output-redshift/src/main/java/org/embulk/output/RedshiftOutputPlugin.java, embulk-output-redshift/src/main/java/org/embulk/output/redshift/RedshiftOutputConnection.java
Query ->
````
BEGIN TRANSACTION;
DELETE FROM toTable USING fromTables_union
WHERE toTable.mergeKey = fromTablse.mergeKey;
INSERT INTO toTable (fromTables_union);
END TRANSACTION;
````
Is this acceptable?
=> Merge mode for redshift.

embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java, embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcSchema.java, embulk-output-oracle/src/test/java/org/embulk/output/oracle/OracleOutputPluginTest.java, embulk-output-oracle/src/test/java/org/embulk/output/oracle/OracleOutputPluginTestImpl.java, embulk-output-oracle/src/test/resources/oracle/yml/test-lower-column-options.yml, embulk-output-oracle/src/test/resources/oracle/yml/test-lower-column.yml, embulk-output-oracle/src/test/resources/oracle/yml/test-lower-table.yml
=> Ignore case in table name and column names

embulk-output-jdbc/src/test/java/org/embulk/output/AbstractJdbcOutputPluginTest.java, embulk-output-oracle/src/test/java/org/embulk/output/oracle/OracleOutputPluginTest.java
Fix some problems in test for embulk-output-oracle
=> Fix embulk-output-oracle test

embulk-output-sqlserver/README.md, embulk-output-sqlserver/build.gradle, embulk-output-sqlserver/src/main/java/org/embulk/output/SQLServerOutputPlugin.java, embulk-output-sqlserver/src/main/java/org/embulk/output/sqlserver/SQLServerOutputConnector.java, embulk-output-sqlserver/src/test/java/org/embulk/output/sqlserver/SQLServerOutputPluginTest.java, embulk-output-sqlserver/src/test/resources/sqlserver/yml/test-jtds.yml
Same concept for https://github.com/embulk/embulk-input-jdbc/pull/60.
=> Support jtds driver

embulk-output-postgresql/src/main/java/org/embulk/output/postgresql/PostgreSQLOutputConnection.java
This PR will fix the issue #127 .
=> Support varchar without length specifier in PostgreSQL

build.gradle
Same as https://github.com/embulk/embulk-input-jdbc/blob/master/build.gradle
=> Enabled to build in Windows

embulk-output-redshift/README.md, embulk-output-redshift/src/main/java/org/embulk/output/redshift/RedshiftCopyBatchInsert.java
By this PR we can use S3 bucket whose region is different from Redshift region.
=> Specify S3 Region in embulk-output-redshift

embulk-output-redshift/src/main/java/org/embulk/output/redshift/RedshiftOutputConnection.java
This PR will fix the issue https://github.com/embulk/embulk/issues/486 .
=> Specify columns to insert in embulk-output-redshift merge

embulk-output-oracle/src/main/java/org/embulk/output/oracle/oci/OCI.java, embulk-output-oracle/src/main/java/org/embulk/output/oracle/oci/OCIWrapper.java, embulk-output-oracle/src/test/java/org/embulk/output/oracle/OracleOutputPluginTest.java
=> Supported OCI_SUCCESS_WITH_INFO

embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
This bug was embedded in https://github.com/embulk/embulk-output-jdbc/pull/141 ...
=> Fixed error when inserting no record

embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java, embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcOutputConnection.java
#147 embeds another bug.
This PR fixes the problem.
=> Fixed error when inserting no record (2)

build.gradle, embulk-output-redshift/README.md, embulk-output-redshift/build.gradle, embulk-output-redshift/src/main/java/org/embulk/output/RedshiftOutputPlugin.java, embulk-output-redshift/src/main/java/org/embulk/output/redshift/RedshiftCopyBatchInsert.java
Hello.
We use embulk-output-redshift.
I want use IAM instance profile.
This PR use DefaultAWSCredentialsProviderChain.
``` java
public DefaultAWSCredentialsProviderChain() {
super(new EnvironmentVariableCredentialsProvider(),
new SystemPropertiesCredentialsProvider(),
new ProfileCredentialsProvider(),
new InstanceProfileCredentialsProvider());
}
```
=> allow access_key_id and secrett_access_key is null.

embulk-output-postgresql/src/main/java/org/embulk/output/postgresql/PostgreSQLOutputConnection.java
=> Support PostgreSQL numeric type without precision

embulk-output-redshift/src/main/java/org/embulk/output/RedshiftOutputPlugin.java
=> Support upper case table name in Redshift

embulk-output-redshift/src/main/java/org/embulk/output/redshift/RedshiftOutputConnection.java
=> Add temp table name on subquery select.

embulk-output-db2/src/main/java/org/embulk/output/db2/DB2OutputConnection.java, embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java, embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/BatchInsert.java, embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcOutputConnection.java, embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/StandardBatchInsert.java, embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/TableIdentifier.java, embulk-output-mysql/README.md, embulk-output-mysql/src/main/java/org/embulk/output/MySQLOutputPlugin.java, embulk-output-mysql/src/main/java/org/embulk/output/mysql/MySQLOutputConnection.java, embulk-output-oracle/src/main/java/org/embulk/output/OracleOutputPlugin.java, embulk-output-oracle/src/main/java/org/embulk/output/oracle/DirectBatchInsert.java, embulk-output-oracle/src/main/java/org/embulk/output/oracle/OracleOutputConnection.java, embulk-output-postgresql/src/main/java/org/embulk/output/postgresql/PostgreSQLCopyBatchInsert.java, embulk-output-postgresql/src/main/java/org/embulk/output/postgresql/PostgreSQLOutputConnection.java, embulk-output-redshift/src/main/java/org/embulk/output/redshift/RedshiftCopyBatchInsert.java, embulk-output-redshift/src/main/java/org/embulk/output/redshift/RedshiftOutputConnection.java, embulk-output-sqlserver/src/main/java/org/embulk/output/sqlserver/NativeBatchInsert.java, embulk-output-sqlserver/src/main/java/org/embulk/output/sqlserver/SQLServerOutputConnection.java
This PR will solve the issue #164 .
I'll support other DBMSs later.
=> Enable to specify temp database for MySQL

embulk-output-mysql/README.md, embulk-output-sqlserver/README.md, embulk-output-sqlserver/src/main/java/org/embulk/output/SQLServerOutputPlugin.java, embulk-output-sqlserver/src/main/java/org/embulk/output/sqlserver/SQLServerOutputConnection.java, embulk-output-sqlserver/src/main/java/org/embulk/output/sqlserver/SQLServerOutputConnector.java
- Support schema
- Fix the problem that causes an error when same table name exists in the another schema.
- Support temp_schema
- After merging #177, SQL Server replace mode doesn't work. This PR will fix it.
=> Support schema for SQL Server

.travis.yml, ci/travis_mysql.yml, ci/travis_postgresql.yml
@hito4t @muga Although no tests may be executed yet, just adding configurations, and compiling there. Can you have a look?
=> Enable Travis CI

embulk-output-sqlserver/src/main/java/org/embulk/output/sqlserver/nativeclient/NativeClientWrapper.java
https://github.com/embulk/embulk-output-jdbc/issues/213
=> Stop reusing pointers in Native Client Wrapper

embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java, embulk-output-postgresql/src/main/java/org/embulk/output/PostgreSQLOutputPlugin.java, embulk-output-redshift/src/main/java/org/embulk/output/RedshiftOutputPlugin.java
=> Generate another temporary table name when already exists

embulk-output-redshift/README.md, embulk-output-redshift/src/main/java/org/embulk/output/RedshiftOutputPlugin.java, embulk-output-redshift/src/main/java/org/embulk/output/redshift/RedshiftCopyBatchInsert.java
This PR will resolve the issue #215.
=> Add option not to delete embulk-output-redshift temporary files on S3

build.gradle, embulk-output-db2/build.gradle, embulk-output-db2/src/main/java/org/embulk/output/DB2OutputPlugin.java, embulk-output-db2/src/test/java/org/embulk/output/db2/DB2OutputPluginTest.java, embulk-output-jdbc/src/main/java/org/embulk/output/JdbcOutputPlugin.java, embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java, embulk-output-mysql/README.md, embulk-output-mysql/build.gradle, embulk-output-mysql/src/main/java/org/embulk/output/MySQLOutputPlugin.java, embulk-output-mysql/src/main/java/org/embulk/output/mysql/MySQLOutputConnector.java, embulk-output-oracle/build.gradle, embulk-output-oracle/src/main/java/org/embulk/output/OracleOutputPlugin.java, embulk-output-oracle/src/main/java/org/embulk/output/oracle/oci/OCIWrapper.java, embulk-output-oracle/src/test/java/org/embulk/output/oracle/OracleTests.java, embulk-output-postgresql/README.md, embulk-output-postgresql/build.gradle, embulk-output-postgresql/src/main/java/org/embulk/output/PostgreSQLOutputPlugin.java, embulk-output-postgresql/src/main/java/org/embulk/output/postgresql/PostgreSQLOutputConnector.java, embulk-output-sqlserver/build.gradle, embulk-output-sqlserver/src/main/java/org/embulk/output/SQLServerOutputPlugin.java
ad embulk-input-jdbc did.
https://github.com/embulk/embulk-input-jdbc/pull/116
https://github.com/embulk/embulk-input-jdbc/pull/117
=> Enabled to change MySQL/PostgreSQL JDBC driver 

embulk-output-postgresql/src/main/java/org/embulk/output/postgresql/AbstractPostgreSQLCopyBatchInsert.java, embulk-output-redshift/src/main/java/org/embulk/output/redshift/RedshiftCopyBatchInsert.java
The PR will fix the issue #230 .
=> Enable to insert \r , \n and \t into Redshift

embulk-output-db2/README.md, embulk-output-jdbc/README.md, embulk-output-mysql/README.md, embulk-output-oracle/README.md, embulk-output-postgresql/README.md, embulk-output-redshift/README.md, embulk-output-sqlserver/README.md
I added colon in README "Configuration" part.
=> Add missing colon in README.

embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcOutputConnection.java
If multiple embulk clients were executed concurrently, and the target table had not exist, both clients might execute `CREATE TABLE` at the same time.
Then eigther one will cause an exception.
But the exception should be ignored because the target table was created successfully.
=> Support concurrent execution of 'CREATE TABLE'

build.gradle, embulk-output-db2/gradle/dependency-locks/embulkPluginRuntime.lockfile, embulk-output-jdbc/gradle/dependency-locks/embulkPluginRuntime.lockfile, embulk-output-mysql/gradle/dependency-locks/embulkPluginRuntime.lockfile, embulk-output-oracle/gradle/dependency-locks/embulkPluginRuntime.lockfile, embulk-output-postgresql/gradle/dependency-locks/embulkPluginRuntime.lockfile, embulk-output-redshift/gradle/dependency-locks/embulkPluginRuntime.lockfile, embulk-output-sqlserver/gradle/dependency-locks/embulkPluginRuntime.lockfile
embulk-util-timestamp:0.2.0 had a problem in formatting time zones with "%Z".
=> Update embulk-util-timestamp to 0.2.1

embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java, embulk-output-jdbc/src/test/java/org/embulk/output/jdbc/AbstractJdbcOutputPluginTest.java, embulk-output-jdbc/src/test/java/org/embulk/output/jdbc/TestJdbcOutputPlugin.java, embulk-output-jdbc/src/test/java/org/embulk/output/jdbc/TimestampFormatTest.java, embulk-output-jdbc/src/test/java/org/embulk/output/jdbc/tester/EmbulkPluginTester.java
=> Make temp tables suffix length flexible

.github/workflows/check.yml
=> Run GitHub Actions on the Pull request.
