- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
Because column types vary by DBMS, it is needed that subclass of the AbstractJdbcOutputPlugin class can extend the ColumnSetterFactory class.
> Enable subclasses of AbstractJdbcOutputPlugin to extend ColumnSetterFactory

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcOutputConnection.java
Add createTable method for subclasses of the JdbcOutputConnection class, because some DBMSs such as Oracle doesn't have "CREATE TABLE IF NOT EXISTS" statement.
> Add createTable method for subclasses of JdbcOutputConnection

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcOutputConnection.java
Some DBMSs such as Oracle don't have "CREATE/DROP TABLE IF EXISTS" statement.
So it's convenient if the JdbcOutputConnection class offers a method to check if a table exists.
> Add tableExists method for subclasses of JdbcOutputConnection

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcOutputConnection.java
Add dropTable method for subclasses of the JdbcOutputConnection class, because some DBMSs such as Oracle don't have "DROP TABLE IF NOT EXISTS" statement.
And modify replaceTable method to call dropTableIfExists method internally.
> Add dropTable method for subclasses of JdbcOutputConnection

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcOutputConnection.java
Because Oracle allows only 30 character for a table name, it is a bit difficult to generate a unique table name.
I've implemented the generateSwapTableName method by generating a swap table name using an original table name and a sequential number, and checking if the table name exists.
https://github.com/hito4t/embulk-output-oracle/blob/branch1/src/main/java/org/embulk/output/OracleOutputPlugin.java
>  Make tableExists method public for Oracle

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
This commit fixes handling of non-existent input and target column.
Could you review this pull request?
> Fix handling of non-existent column.

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcColumn.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcOutputConnection.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/StandardBatchInsert.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/setter/ColumnSetter.java
- embulk-output-mysql/src/main/java/org/embulk/output/MySQLOutputPlugin.java
- embulk-output-mysql/src/main/java/org/embulk/output/mysql/MySQLBatchUpsert.java
- embulk-output-mysql/src/main/java/org/embulk/output/mysql/MySQLOutputConnection.java
- embulk-output-oracle/src/main/java/org/embulk/output/OracleOutputPlugin.java
- embulk-output-postgresql/src/main/java/org/embulk/output/PostgreSQLOutputPlugin.java
- embulk-output-postgresql/src/main/java/org/embulk/output/postgresql/PostgreSQLOutputConnection.java
- embulk-output-postgresql/src/main/java/org/embulk/output/postgresql/PostgresqlBatchUpsert.java
- embulk-output-redshift/src/main/java/org/embulk/output/RedshiftOutputPlugin.java
This PR implements `merge` mode to output records into database by executing upsert query.
The summary of each databases is as below:
1. mysql
- execute INSERT ~ ON DUPLICATE KEY UPDATE query
2. postgresql
- execute WITH query by pk on the tabke
- support for only >=9.1, bacause WITH UPDATE〜 query is supported from this version
3. other databases
- I'm not implemented yet, I'll do it soon.
> support merge mode for mysql/postgresql

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/setter/SkipColumnSetter.java
Implement SkipColumnSetter#nullValue to skip the column and avoid NullPointerException.
<pre>
Caused by: java.lang.NullPointerException
at org.embulk.output.jdbc.setter.ColumnSetter.getSqlType(ColumnSetter.java:34)
at org.embulk.output.jdbc.setter.ColumnSetter.nullValue(ColumnSetter.java:110)
at org.embulk.output.jdbc.setter.ColumnSetter.stringColumn(ColumnSetter.java:83)
at org.embulk.spi.Column.visit(Column.java:57)
</pre>
> Implement SkipColumnSetter#nullValue

- embulk-output-oracle/src/test/resources/yml/test-insert-direct.yml
- embulk-output-oracle/src/test/resources/yml/test-insert-oci-split.yml
- embulk-output-oracle/src/test/resources/yml/test-insert-oci.yml
- embulk-output-oracle/src/test/resources/yml/test-insert.yml
- embulk-output-oracle/src/test/resources/yml/test-replace-long-name.yml
- embulk-output-oracle/src/test/resources/yml/test-replace.yml
- embulk-output-oracle/src/test/resources/yml/test-url.yml
Column names of embulk-output-oracle test table are upper cases, but column names of embulk-output-oracle test ymls were lower cases.
By #21, a yml column which doesn't match exactly a column name of table is skipped.
So I've changed yml column names to upper cases.
> Change column names of embulk-output-oracle test ymls

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
- embulk-output-postgresql/src/main/java/org/embulk/output/PostgreSQLOutputPlugin.java
This PR will fix a problem of insert-mode for postgresql which results from implementation of merge-mode.
Now, too many columns will be written to tmp tsv file by this bug, so I wrote this batch to resolve it.
> fix insert-mode in postgresql doesn't work

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
- embulk-output-oracle/src/main/java/org/embulk/output/OracleOutputPlugin.java
- embulk-output-oracle/src/main/java/org/embulk/output/oracle/OracleOutputConnection.java
- embulk-output-oracle/src/test/java/org/embulk/output/oracle/OracleOutputPluginTest.java
- embulk-output-oracle/src/test/java/org/embulk/output/oracle/OracleOutputPluginTestImpl.java
- embulk-output-oracle/src/test/resources/yml/test-replace-long-name-multibyte.yml
Only OracleJdbcPlugin#generateSwapTableName supported table name length limitation, but other RDMSs also have such limitation.
So I've moved contents of OracleJdbcPlugin#generateSwapTableName to AbstractJdbcPlugin.
In addition, I've corrected embulk-output-oracle to measure length of multibyte table name correctly.
> Support swap table name length limitation for all RDMSs

- embulk-output-oracle/README.md
We need YourKit to improve the performance of embulk-output-oracle.
In order to use YourKit open source project license, we should put acknowledgment for YourKit on the project web site.
The email from YourKit team is as follows.
> we require to place on the project web site a small free-form text acknowledgment/testimonial.
> 
> The acknowledgment should contain:
> 
> - Attached YourKit logo and text that your open source project is using YourKit profiler. Alternatively logo hosted at https://www.yourkit.com/images/yklogo.png
can be used.
> 
> - Should contain a reference to YourKit web site.
> 
> For example:
> "
> YourKit supports open source projects with its full-featured Java Profiler.
> YourKit, LLC is the creator of <a href="https://www.yourkit.com/java/profiler/index.jsp">YourKit …
> YourKit acknowledgment

- embulk-output-redshift/src/main/java/org/embulk/output/redshift/RedshiftCopyBatchInsert.java
Redshiftのvarcharとcharカラムに"N"を登録すると、NULLになってしまう問題を修正。
> Fixed an issue where "N" is registered in NULL.

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/BatchInsert.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/StandardBatchInsert.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/setter/ColumnSetterFactory.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/setter/PassThroughColumnSetter.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/setter/SqlDateColumnSetter.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/setter/SqlTimeColumnSetter.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/setter/SqlTimestampColumnSetter.java
- embulk-output-oracle/src/main/java/org/embulk/output/oracle/DirectBatchInsert.java
- embulk-output-oracle/src/test/java/org/embulk/output/oracle/OracleOutputPluginTestImpl.java
- embulk-output-postgresql/src/main/java/org/embulk/output/PostgreSQLOutputPlugin.java
- embulk-output-postgresql/src/main/java/org/embulk/output/postgresql/AbstractPostgreSQLCopyBatchInsert.java
- embulk-output-postgresql/src/main/java/org/embulk/output/postgresql/PostgreSQLOutputConnection.java
JDBC spec defines that `PreparedStatement#setTime`, `#setDate`, and `#setTime` use JVM's default time zone if Calendar instance is not set. 
https://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html#setTimestamp-int-java.sql.Timestamp-java.util.Calendar-
>> If no Calendar object is specified, the driver uses the default timezone, which is that of the virtual machine running the application.
This change forces them to use default_timezone or column_options.timezone parameter so that behavior becomes independent from execution environment.
As a part of change, embulk-output-postgresql uses TIMESTAMP WITH TIME ZONE type by default instead of TIMESTAMP type.
> Make timestamp column setters independent from JVM's default time zone

- embulk-output-postgresql/README.md
- embulk-output-postgresql/build.gradle
- embulk-output-postgresql/src/main/java/org/embulk/output/PostgreSQLOutputPlugin.java
Setting `ssl: true` sets ssl=true and sslfactory=org.postgresql.ssl.NonValidatingFactory
JDBC options.
> Add ssl: option to postgresql

- embulk-output-oracle/src/main/java/org/embulk/output/oracle/OracleOutputConnection.java
- embulk-output-oracle/src/test/resources/yml/test-insert.yml
If try to output into a table with VARCHAR2 column in `mode: insert`, embulk-output-oracle will fail to create a temporary table.
(work around is to define type in column_options of yml)
This PR fixes the problem.
> Support Oracle VARCHAR2 in creating temporary table

- embulk-output-redshift/README.md
- embulk-output-redshift/src/main/java/org/embulk/output/RedshiftOutputPlugin.java
Because it is not implemented. (#72)
> Remove merge mode in embulk-output-redshift

- embulk-output-oracle/src/main/java/org/embulk/output/oracle/oci/OCIWrapper.java
Actually, charset of object names depends on client environment.
Namely, if a client with UTF-8 creates multibyte table name, and another client with EUC selects the table, it will fail.
> Support multibyte object name in Oracle OCI mode

- embulk-output-sqlserver/src/main/java/org/embulk/output/SQLServerOutputPlugin.java
When using integrated security, user and password may not be set.
> SQL Server : null check for user and password

- build.gradle
`./gradlew findbugsMain` task (automatically executed with `./gradlew check`) generates reports at embulk-output-*/build/reports/findbugs/main.html.
Example: https://gyazo.com/f0b412179649ef58c57224dd6aef77ec.png
> Enable findbugs

- embulk-output-oracle/src/main/java/org/embulk/output/oracle/DirectBatchInsert.java
The `DirectBatchInsert#close` method is called by the `PluginPageOutput#close` method.
The `PluginPageOutput#close` method seems to be called multiple times.
> Check not to close OCI twice

- build.gradle
- embulk-output-jdbc/src/main/java/org/embulk/output/JdbcOutputPlugin.java
- embulk-output-redshift/README.md
- embulk-output-redshift/src/main/java/org/embulk/output/RedshiftOutputPlugin.java
- embulk-output-redshift/src/main/java/org/embulk/output/redshift/RedshiftCopyBatchInsert.java
The Redshift driver only supports "Federated" credentials, which simply means temporary S3 credentials. This requires an AWS user account and certain configurations. This is more complex than needed. I had two problems using it:
1) in my installation we use "headless" key pairs which do not include a user name, and
2) I could not get the plugin to work using my own personal account, even though I set all of the right permissions.
Note that the other plugins which access S3 only require access&secret keys. This is the only Embulk plugin that requires Federated credentials.
This PR allows the user to give AWS access&secret keys only. The 'iam_user_name' configuration entry can be left out, or have '' as its value.
Issue: https://github.com/embulk/embulk-output-jdbc/issues/85
> S3 creds allow no iam_user_name

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcOutputConnection.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/StandardBatchInsert.java
Comment says "caller should close the connection", but no one closes connection.
> Close connection

- embulk-output-oracle/src/main/java/org/embulk/output/oracle/DirectBatchInsert.java
- embulk-output-oracle/src/main/java/org/embulk/output/oracle/oci/OCI.java
- embulk-output-oracle/src/main/java/org/embulk/output/oracle/oci/OCIManager.java
- embulk-output-oracle/src/main/java/org/embulk/output/oracle/oci/OCIWrapper.java
- embulk-output-oracle/src/main/java/org/embulk/output/oracle/oci/RowBuffer.java
- embulk-output-oracle/src/test/java/org/embulk/output/oracle/OracleOutputPluginTest.java
- embulk-output-oracle/src/test/java/org/embulk/output/oracle/OracleOutputPluginTestImpl.java
- embulk-output-oracle/src/test/resources/oracle/yml/test-insert-direct-oci-method-multibyte.yml
If keys already exist when loading records by Oracle OCI, the index becomes unusable but no exception is thrown.
We should check if index is usable and throw an exception.
> Exception for duplicate keys in Oracle OCI

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
- embulk-output-mysql/src/main/java/org/embulk/output/MySQLOutputPlugin.java
Some insert errors are retryable.
For example, I use MySQL and multi threaded embulk-output-mysql, deadlock error occurs often.
If plugin can retry transaction, plugin can continue to process.
I think that such situation occurs only when `mode` is `merge_direct` or `merge` (maybe only MySQL).
But I am in trouble.
> Implements retryable execution feature

- embulk-output-redshift/src/main/java/org/embulk/output/RedshiftOutputPlugin.java
This fixes a bug introduced in https://github.com/embulk/embulk-output-jdbc/pull/117.
Without escaping, this gives the following error:
```
Error: org.embulk.config.ConfigException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'disable': was expecting ('true', 'false' or 'null')
```
output to Redshift is currently broken on master due to this if someones doesn't put `ssl` in the configuration section
> Default value for SSL should be escaped

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/StandardBatchInsert.java
If `StandardBatchInsert#close` is called before `prepare`, NullPointerException will be thrown.
> Fix NullPointerException in StandardBatchInsert#close

- embulk-output-postgresql/src/main/java/org/embulk/output/postgresql/PostgreSQLOutputConnection.java
With certain datatypes (timestamp, bigint, uuid...) direct merge fails, because postgres doesnt how to work with the data given in the `WITH S AS` select
`ERROR: XX000: failed to find conversion function from unknown to ...`
This patch does cast on all the values.
> merge_direct fixes for postgresql 

- embulk-output-redshift/build.gradle
With current sdk version, error raised with that message.
`Error: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot create enum from ap-northeast-2 value!`
> Upgrade aws-java-sdk libraries version for supporting newer region.

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcOutputConnection.java
- embulk-output-oracle/src/main/java/org/embulk/output/oracle/OracleOutputConnection.java
- embulk-output-sqlserver/src/main/java/org/embulk/output/sqlserver/SQLServerOutputConnection.java
An intermediate table name generated by `AbstractJdbcOutputPlugin` can already exist.
In this case `AbstractJdbcOutputPlugin` will drop the table, so the owner of the table will not work properly.
By this PR, `AbstractJdbcOutputPlugin` always create intermediate tables which don't exist yet.
> Fix intermediate table duplication

- embulk-output-mysql/src/main/java/org/embulk/output/MySQLOutputPlugin.java
- embulk-output-mysql/src/main/java/org/embulk/output/MySQLTimeZoneComparison.java
- embulk-output-mysql/src/main/java/org/embulk/output/mysql/MySQLOutputConnection.java
@hito4t 
This is the same implementation https://github.com/embulk/embulk-input-jdbc/pull/106
This PR enable the embulk-output-mysql compare between a server and client timezone. 
After comparison, output the following logs. 
```
2017-05-24 21:18:13.840 +0900 [WARN] (0001:transaction): The client timezone(Asia/Tokyo) is different from the server timezone(UTC). The plugin will store wrong datetime values.
2017-05-24 21:18:13.841 +0900 [WARN] (0001:transaction): You may need to set options `useLegacyDatetimeCode` and `serverTimezone`
2017-05-24 21:18:13.841 +0900 [WARN] (0001:transaction): Example. `options: { useLegacyDatetimeCode: false, serverTimezone: UTC }`
2017-05-24 21:18:13.841 +0900 [WARN] (0001:transaction): The plugin will set `useLegacyDatetimeCode=false` by default in future. …
```
> Compare MySQL server and client time method.

- embulk-output-oracle/README.md
- embulk-output-oracle/src/main/java/org/embulk/output/OracleOutputPlugin.java
- embulk-output-oracle/src/main/java/org/embulk/output/oracle/OracleOutputConnection.java
- Support temp_schema
- After merging #177, Oracle replace mode doesn't work. This PR will fix it.
> Support temp_schema for Oracle

- embulk-output-postgresql/README.md
- embulk-output-postgresql/src/main/java/org/embulk/output/PostgreSQLOutputPlugin.java
- embulk-output-postgresql/src/main/java/org/embulk/output/postgresql/PostgreSQLOutputConnection.java
- Support temp_schema
- After merging #177, PostgreSQL replace mode doesn't work. This PR will fix it.
> Support temp_schema for PostgreSQL

- embulk-output-redshift/README.md
- embulk-output-redshift/src/main/java/org/embulk/output/RedshiftOutputPlugin.java
- embulk-output-redshift/src/main/java/org/embulk/output/redshift/RedshiftOutputConnection.java
- Support temp_schema
- After merging #177, Redshift replace mode doesn't work. This PR will fix it.
> Support temp_schema for Redshift

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcOutputConnection.java
- embulk-output-mysql/src/main/java/org/embulk/output/mysql/MySQLOutputConnection.java
his PR the changes the following
* Output the JDBC Driver version. 
* Add MySQL Connector/J warning before an update Connector/J. 
This PR is the same https://github.com/embulk/embulk-input-jdbc/pull/110
@hito4t I wrote `con.showDriverVersion` in the `begin` method. 
It called from `transaction` and `resume`.
What do you think it is the proper place?
Output examples are below.
```
2017-06-25 10:31:32.318 +0900 [INFO] (0001:transaction): Using JDBC Driver PostgreSQL 9.4 JDBC4.1 (build 1205)
```
```
2017-06-25 10:32:53.356 +0900 [INFO] (0001:transaction): Using JDBC Driver mysql-connector-java-5.1.34 ( Revision: jess.balint@oracle.com-20141014163213-wqbwpf1ok2kvo1om )
2017-06-25 10:32:53.357 +0900 [WARN] (0001:transaction): This plugin will update MySQL Connector/J version in the near …
```
> Output JDBC driver version and MySQL Connector/J update warning

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcOutputConnection.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/Ssl.java
- embulk-output-mysql/README.md
- embulk-output-mysql/src/main/java/org/embulk/output/MySQLOutputPlugin.java
- embulk-output-mysql/src/main/java/org/embulk/output/mysql/MySQLOutputConnection.java
- embulk-output-redshift/src/main/java/org/embulk/output/RedshiftOutputPlugin.java
Add MySQL SSL option. 
This is the same feature https://github.com/embulk/embulk-input-jdbc/pull/109
**Caution**
This PR depends on #182.
Please merge it before this PR.
> Add MySQL ssl option

- embulk-output-redshift/README.md
- embulk-output-redshift/src/main/java/org/embulk/output/redshift/RedshiftOutputConnection.java
There was an error in `buildCollectMergeSql` so that if any row from the temporary table existed in the target table, **no rows** from the temporary table were inserted into the target table.
I fixed that bug here, and updated the README to reflect the actual behavior (update and then insert, not delete and then insert).
> Fix Redshift output plugin merge mode

- embulk-output-redshift/README.md
As the description says, I just added a warning. I had a situation where one of my merge keys (I was using three) was allowed to be `NULL` and it didn't work because Redshift can't compare `NULL = NULL`.
Unfortunately, I don't think there's a way to support `NULL` merge keys.
> Add note warning about NULL merge keys

- embulk-output-redshift/src/main/java/org/embulk/output/redshift/RedshiftOutputConnection.java
Right now we're hitting issues where we're getting errors when using replace about tables already existing. I believe that the `DROP TABLE` command is failing and we're just not seeing the error it returns. `DROP TABLE IF EXISTS` is available, this PR uses it.
I haven't tested this yet on our deployment, will be doing that asap.
> Use DROP TABLE IF EXISTS and stop ignoring exceptions

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcColumnOption.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/setter/ColumnSetterFactory.java
Trying to workaround the deprecation on the Embulk core side. The same as https://github.com/embulk/embulk-input-jdbc/pull/121
@hito4t @muga Can you have a look?
> Use traditional constructors of TimestampFormatter and TimestampParser against deprecation: Fix #190

- build.gradle
- embulk-output-redshift/README.md
- embulk-output-redshift/build.gradle
I  tried using this plugin on ECS Container, but it did not work.
In aws-java-sdk, this library should use `ContainerCredentialsProvider` class, but current release does not support it.
On the other hand, latest release of embulk-util-aws-credentials (0.2.9+) supports `DefaultAWSCredentialsProviderChain` with configuration value that is ’”default"'. Please support it.
regards.
> Upgrade Dependency embulk-util-aws-credentials to 0.2.21

- embulk-output-oracle/src/main/java/org/embulk/output/oracle/DirectBatchInsert.java
`org.embulk.output.oracle.DirectBatchInsert` class supports `java.sql.Types.NUMERIC` .
> Support java.sql.Types.NUMERIC in Oracle OCI

- embulk-output-redshift/build.gradle
AWS Signature Version 2 is not support after June 24, 2019.
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html
> Amazon S3 supports only AWS Signature Version 4 in most AWS Regions. In some of the older AWS Regions, Amazon S3 supports both Signature Version 4 and Signature Version 2. However, Signature Version 2 is being deprecated, and the final support for Signature Version 2 will end on June 24, 2019. For more information about the end of support for Signature Version 2, see AWS Signature Version 2 Deprecation for Amazon S3.
this pull request is update aws java sdk.
I confirmed in S3's object log that this change made AWS Signature Version 4 to be used.
> update aws-java-sdk version

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
- embulk-output-mysql/src/test/java/org/embulk/output/mysql/RetryTest.java
embulk-output-jdbc holds a list of records to insert for retry.
But incorrect records will be inserted in re-retry because the list won't updated in retry.
This PR fix that by updating the list in retry.
> Fix a bug that incorrect records will be inserted in re-retry

- embulk-output-sqlserver/README.md
- embulk-output-sqlserver/src/main/java/org/embulk/output/SQLServerOutputPlugin.java
Currently I meet some trouble after submits the insert query to the server, the job waits for the response but somehow can’t get it and wait forever.
It can be considered as a bug of jTDS lib  as mentioned here: 
https://sourceforge.net/p/jtds/discussion/104389/thread/c3979289/
https://sourceforge.net/p/jtds/bugs/520/ (closed but not resolved)
I think we should introduce timeout for this case. 
How to test this: 
Let's say we start a new transaction and lock the same table when the job is running. It will wait there
`BEGIN TRANSACTION
SELECT * FROM ableTest_0000016c24cdd32d_embulk000 WITH (TABLOCKX, HOLDLOCK)
WHERE 0 = 1
WAITFOR DELAY '02:00'
ROLLBACK TRANSACTION`
> Introduce connection_timeout and socket_timeout to sqlserver

- embulk-output-sqlserver/README.md
- embulk-output-sqlserver/build.gradle
- embulk-output-sqlserver/src/main/java/org/embulk/output/SQLServerOutputPlugin.java
- embulk-output-sqlserver/src/main/java/org/embulk/output/sqlserver/SQLServerOutputConnection.java
- embulk-output-sqlserver/src/main/java/org/embulk/output/sqlserver/setter/SQLServerColumnSetterFactory.java
- embulk-output-sqlserver/src/test/java/org/embulk/output/sqlserver/BasicTest.java
- embulk-output-sqlserver/src/test/java/org/embulk/output/sqlserver/SQLServerTests.java
`JTDS` driver is quite old and not maintained for a long time and `mssql` driver is now open source.
We should keep the output syn with input also by replacing `JTDS` by `mssql` driver.
> Replace jtds by mssql:jdbc

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/TableIdentifier.java
- embulk-output-sqlserver/src/main/java/org/embulk/output/sqlserver/NativeBatchInsert.java
- embulk-output-sqlserver/src/main/java/org/embulk/output/sqlserver/nativeclient/NativeClientWrapper.java
The `schema` and `temp_schema` configuration properties are ignored when using `insert_method: native`. Presumably they default to the user's default schema, as [bcp_init](https://docs.microsoft.com/lb-lu/sql/relational-databases/native-client-odbc-extensions-bulk-copy-functions/bcp-init?view=sql-server-ver15) is called with the `table` parameter set to `[db_name]..[table_name]`.
The fix is trivial, but note that I've only been able to test this manually and only in `mode: insert_direct`. It _seems_ that `loadTable.getSchemaName()` is not supposed to be null, but it's hard to be sure. Please check if this is correct.
> Support non-default schema in MSSQL "native" mode

- embulk-output-mysql/README.md
I would added create_table_constraint, column options example in README "Advanced configuration" part.
ref: https://qiita.com/play-life/items/2805ecb12ede6fa04c44#comment-d5e32180fac106adf60c
> Add: create_table_constraint option usage in README

- embulk-output-postgresql/README.md
- embulk-output-postgresql/src/main/java/org/embulk/output/PostgreSQLOutputPlugin.java
- embulk-output-postgresql/src/main/java/org/embulk/output/postgresql/PostgreSQLOutputConnection.java
- embulk-output-postgresql/src/main/java/org/embulk/output/postgresql/PostgreSQLOutputConnector.java
- embulk-output-postgresql/src/test/java/org/embulk/output/postgresql/BasicTest.java
PostgreSQL supports inheritance of user roles. Members of a parent role
can switch its role to the parent role. By changing role before running
CREATE statements, the parent role is used as the owner of the new
objects. This is useful especially if we adopting following operation:
(1) owner of objects are always a parent role and members can be rotated
or deleted at anytime, (2) the owner of tables loaded by a bulk loading
is always the same parent role while login passwords are managed per
person basis.
This operation is more effecitive if the members are created with
NOINHERIT option.
This change adds a new option `set_role: <ROLE_NAME>` to
embulk-output-postgresql support the use case.
Although MySQL and Oracle also support SET ROLE syntax, this change
doesn't change code for them as …
> Adding support for SET ROLE to PostgreSQL

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcColumnOption.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/setter/ColumnSetterFactory.java
- embulk-output-mysql/src/test/java/org/embulk/output/mysql/BasicTest.java
- embulk-output-postgresql/src/main/java/org/embulk/output/PostgreSQLOutputPlugin.java
- embulk-output-postgresql/src/main/java/org/embulk/output/postgresql/setter/PostgreSQLColumnSetterFactory.java
- embulk-output-sqlserver/src/main/java/org/embulk/output/SQLServerOutputPlugin.java
Counter to the past changes in #275. #275 replaced Joda-Time's `DateTimeZone` to `String`, and introduced an explicit check against invalid time zones.
We have `embulk-util-config:0.3.0` for `embulk-input-jdbc` now by #292. It has an additional Jackson `Module` to map an Embulk config into `java.time.ZoneId` directly with some validation.
* https://github.com/embulk/embulk-util-config/pull/16
* https://github.com/embulk/embulk-util-config/pull/22
We can replace the explicit check against invalid time zones by `ZoneIdModule`.
This PR follows #292.
> Map an Embulk config directly to ZoneId with embulk-util-config's ZoneIdModule

- embulk-output-jdbc/build.gradle
- embulk-output-mysql/build.gradle
- embulk-output-postgresql/build.gradle
- embulk-output-redshift/build.gradle
- embulk-output-sqlserver/build.gradle
We're going to release JARs of `embulk-output-jdbc/...` to Maven Central from 0.10.0 (#294).
Maven Central needs the `<developers>` section available in `pom.xml`. In this chance, trying to nominate developers who have contributed a important portion in `embulk-input-jdbc/mysql/postgresql/redshift` from the Git log.
> Nominate developers in embulk-output-jdbc/mysql/postgresql/redshift/sqlserver

- .github/workflows/build.yml
- embulk-output-sqlserver/src/main/java/org/embulk/output/sqlserver/setter/SQLServerColumnSetterFactory.java
I found that `embulk-output-sqlserver` was failing to compile when I tried to release 0.10.0. We were not able to detect it beforehand as it was not tested in GitHub Actions.
This PR fixes the compile error, and adds "build-only" check in GitHub Actions for the time being.
Testing `embulk-output-sqlserver` on GitHub Actions would be addressed in #280 later...
> Fix a compile error in embulk-output-sqlserver

- .github/workflows/check.yml
* Use `actions/checkout@v3`, `actions/setup-java@v3` and `actions/upload-artifact@v3`
* Use temurin JDK (It's the same JDK as the Embulk repository.)
* Run on push and pull_request (from a forked repository only)
* Add gradle cache.
* Add `fail-fast` strategy.
@dmikurube Could you take a look when you get a chance?
Especially, `gradle` and `strategy` part.
> Check with GitHub Actions v3

- .github/workflows/main.yml
The mainstream of Git default branches is now `main`, not `master`.
https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/
But, changing the default branch is often not very easy in historical repositories because some external environments often expect an older conventions.
For a smoother migration, this pull request is a trick to sync `master` to `main` automatically so that external environments can catch up with `main` while `main` is synchronized to `master`.
> Sync the "master" branch to "main"

- embulk-output-jdbc/README.md
- embulk-output-mysql/README.md
- embulk-output-postgresql/README.md
- embulk-output-redshift/README.md
- embulk-output-sqlserver/README.md
mode:tuncate_insert does not actually use the truncate statement, it executes the delete statement
https://github.com/embulk/embulk-output-jdbc/blob/dfb2192cd0162ac32b9111f1de7f28177e4cf902/embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java#L890-L897
https://github.com/embulk/embulk-output-jdbc/blob/dfb2192cd0162ac32b9111f1de7f28177e4cf902/embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcOutputConnection.java#L386-L417
https://github.com/embulk/embulk-output-jdbc/blob/dfb2192cd0162ac32b9111f1de7f28177e4cf902/embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcOutputConnection.java#L419-L427
https://github.com/embulk/embulk-output-jdbc/pull/321#issuecomment-1630121862
I have updated description to your comment's
> truncate insert description update

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/MemoryRecord.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/PageReaderRecord.java
in order to avoid to abort retrying.
Because a timestamp is casted to Instant and retain it on MemoryRecord,
but MemoryRecord tries to cast from Timestamp to Instant and raises ClassCastException.
And so, retryExecutor abort on the first retry.
error log with #325 
```
2023-10-02 09:51:58.971 2023-10-02 09:51:58.971 +0000 [INFO] (0019:task-0012): > 0.86 seconds (loaded 3,744 rows in total)
2023-10-02 09:51:59.375 2023-10-02 09:51:59.376 +0000 [ERROR] (0018:task-0013): Operation failed (first exception:{SQLState=1213, ErrorCode=40001})
2023-10-02 09:51:59.375 java.sql.BatchUpdateException: Deadlock found when trying to get lock; try restarting transaction
2023-10-02 09:51:59.375 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2023-10-02 …
```
> fix: fix double casting on `getTimestamp`

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
If a raised exception changes during retry executions and the exception is not retryable, the retrying is aborted instantly, but the information of the last exception is lost, because RetryExecutor throws only the first exception and OnRetry hook doesn't log about the last exception.
For example, like this:
```
2023-09-06 18:56:18.365 +0000 [WARN] (0018:task-0010): Operation fai
led (1213:40001), retrying 1/8 after 1 seconds. Message: Deadlock found when trying to get lock; try restarting transaction
2023-09-06 18:56:19.366 +0000 [ERROR] (0018:task-0010): Operation fa
iled (1213:40001)
```
In this situation, it is difficult to identify the root problem, so I would like to change to log also last exception.
> Add logging to avoid loss of information when exception changes during retries

- .github/CODEOWNERS
Similar to https://github.com/embulk/embulk-input-jdbc/pull/253, adding `CODEOWNERS`.
> Add CODEOWNERS as @embulk/jdbc-maintainers

- embulk-output-sqlserver/src/main/java/org/embulk/output/sqlserver/SQLServerOutputConnection.java
Currently, the `embulk-output-sqlserver` mapped `CLOB` to `TEXT` type. This mapping will not work with some Japanese collation. It will display error message like `SQL Error [4188] [S0001]: Column or parameter 'colume1' has type 'text' and collation 'Japanese_XJIS_140_CI_AS'. The legacy LOB types do not support UTF-8 or UTF-16 encodings. Use types varchar(max), nvarchar(max) or a collation which does not have the _SC or _UTF8 flags.`. Moreover, as `TEXT` type is deprecated and removed in the future version (https://learn.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-2016). So this PR will map `CLOB` type to `NVARCHAR(max)` type.
Ref: https://learn.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support?view=sql-serv …
> Use NVARCHAR(max) for CLOB, instead of TEXT, when creating a table in SQLServer

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java
- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcOutputConnection.java
Fixing #312 
I added test code to embulk-output-postgresql in #319.
@dmikurube and @hito4t 
Could you check when you get a chance?
Ref: https://embulk-dev.zulipchat.com/#narrow/stream/352993-embulk/topic/output-postgresql.20.3A.20support.20select.20in.20the.20after_load/near/345032157
> Use execute() instead of executeUpdate() for afterLoad/beforeLoad

- README.md
Java 7 is already an unsupported version.
> Remove the explanation of Java 7.

- embulk-output-redshift/README.md
- embulk-output-redshift/src/main/java/org/embulk/output/RedshiftOutputPlugin.java
- embulk-output-redshift/src/main/java/org/embulk/output/redshift/RedshiftCopyBatchInsert.java
The changes are essentially the same as in [this PR](https://github.com/embulk/embulk-output-jdbc/pull/311).
I've fixed the points commented on in the above review.
> Added max_s3_upload_threads_per_task option to Redshift

- embulk-output-mysql/README.md
- embulk-output-mysql/src/main/java/org/embulk/output/mysql/MySQLOutputConnection.java
This is a re-implementation of
https://github.com/embulk/embulk-output-jdbc/pull/336
with fixed based on the reviews by @hiroyuki-sato in https://github.com/embulk/embulk-output-jdbc/pull/336 applied (Thanks for the review.)
The current implementation for replace mode
* First drops the target table
* Then renames the intermediate table to target table
For databases that have transactional DDL queries, there are no problems with this operation.
Although, MySQL implicitly commits `DROP TABLE` and `RENAME TABLE` which can inadvertently drop the target table, if the `RENAME TABLE` fails, or the operation is aborted in the middle. 
https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html
This pull request aims to make the replace mode safer for MySQL by changing the operation to
* First …
> Swap name + drop instead of drop + rename in MySQL replace mode

- embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/setter/NStringColumnSetter.java
Fix NString value to JSON same as [StringColumnSetter](https://github.com/embulk/embulk-output-jdbc/blob/master/embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/setter/StringColumnSetter.java#L64).
> Fix NString value to JSON

- .github/workflows/check.yml
* Adding PostgreSQL 13 and MySQL 8.3 to GitHub Actions.
* Change JDK image `temurin` to `zulu`.
> Adding PostgreSQL 13 and MySQL 8.3 to GitHub Actions.

- embulk-output-postgresql/src/main/java/org/embulk/output/postgresql/PostgreSQLOutputConnection.java
This pull request is fixes issue #350
> Add getDataLength for numeric without precision
